#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "server_name _;\n\n\trewrite \^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
service nginx start
