#!/usr/bin/env bash
# prints the message infinity and beyond
# indefinitely unless it is killed

# Handle SIGTERM
trap "echo 'I am invincible!!!'" 15


# print the message forever
while true;
do
	echo "To infinity and beyond";
	sleep 2
done
